sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
script: 
  - mvn clean install
before_install:
  - pip install --upgrade pip
  - pip install --user s3cmd
  - pip install --user localstack
  - bash start-localstack.sh

