sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
script: 
  - mvn clean install
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y s3cmd
  - which s3cmd
  - pip install --upgrade pip
  - pip install --user localstack
  - localstack start &

